In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('Gold_Dec_26.csv')
df.head()

,Price,Close,High,Low,Open,Volume
0,Ticker,GC=F,GC=F,GC=F,GC=F,GC=F
1,Date,NaN,NaN,NaN,NaN,NaN
2,2000-08-30,273.8999938964844,273.8999938964844,273.8999938964844,273.8999938964844,0
3,2000-08-31,278.29998779296875,278.29998779296875,274.79998779296875,274.79998779296875,0
4,2000-09-01,277.0,277.0,277.0,277.0,0

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6563 entries, 0 to 6562
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Price   6563 non-null   str
 1   Close   6562 non-null   str
 2   High    6562 non-null   str
 3   Low     6562 non-null   str
 4   Open    6562 non-null   str
 5   Volume  6562 non-null   str
dtypes: str(6)
memory usage: 307.8 KB

Rows 0 and 1 (Ticker GC=F… and Date NaN…). Because of them, every column is read as text, not numbers. I should Load it by skipping the two first Rows 0 ans 1, I reload the file with `skiprows=[1, 2]` to skip these two lines

In [4]:
df = pd.read_csv('Gold_Dec_26.csv', skiprows=[1, 2])
df = df.rename(columns={'Price': 'Date'})
df['Date'] = pd.to_datetime(df['Date'])
df = df.set_index('Date')
df.head()

                 Close        High         Low        Open  Volume
Date
2000-08-30  273.899994  273.899994  273.899994  273.899994       0
2000-08-31  278.299988  278.299988  274.799988  274.799988       0
2000-09-01  277.000000  277.000000  277.000000  277.000000       0
2000-09-05  275.799988  275.799988  275.799988  275.799988       2
2000-09-06  274.200012  274.200012  274.200012  274.200012       0

In [5]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 6561 entries, 2000-08-30 to 2026-10-21
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Close   6561 non-null   float64
 1   High    6561 non-null   float64
 2   Low     6561 non-null   float64
 3   Open    6561 non-null   float64
 4   Volume  6561 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 307.5 KB